apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
commonLabels:
  app: lidarr
resources:
  - service.yaml
  - deployment.yaml
  - ingress.yaml
  - volume.yaml
secretGenerator:
  - name: smb-bighorse
    type: Opaque
    literals:
      - username=k8s
    files:
      - password=secret/password.sops.txt
