apiVersion: v1
kind: Service
metadata:
  name: lidarr-v4
  annotations:
    external-dns.alpha.kubernetes.io/hostname: lidarr.k8s.holywoo.cbannister.xyz
spec:
  selector:
    app: lidarr
  type: LoadBalancer
  loadBalancerIP: 10.1.12.4
  ipFamilies:
    - IPv4
  ports:
    - name: http
      port: 80
      targetPort: web
      protocol: TCP
