apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
commonLabels:
  app: prometheus
resources:
  - helmrelease.yaml
configMapGenerator:
  - name: kube-prometheus-stack-values
    files:
      - values.yaml
  - name: kube-state-metrics-configmap
    files:
      - kube-state-metrics.yaml=./resources/kube-state-metrics.yaml
configurations:
  - kustomizeconfig.yaml
