nameReference:
  - kind: ConfigMap
    version: v1
    fieldSpecs:
      - path: spec/valuesFrom/name
        kind: HelmRelease
  - kind: ConfigMap
    apiVersion: v1
    fieldSpecs:
      - path: spec/valuesFrom/name
        kind: HelmRelease
