apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
commonLabels:
  app: prometheus
resources:
  - helmrelease.yaml
  - ./scrapeconfigs
configMapGenerator:
  - name: kube-prometheus-stack-values
    files:
      - values.yaml
configurations:
  - kustomizeconfig.yaml
