crds:
  enabled: true
cleanPrometheusOperatorObjectNames: true
namespaceOverride: monitoring
prometheus:
  ingress:
    enabled: true
    ingressClassName: internal
    pathType: Prefix
    hosts: &hosts
      - prometheus.cbannister.xyz
    tls:
      - hosts: *hosts
  thanosService:
    enabled: true
  thanosServiceMonitor:
    enabled: true
  prometheusSpec:
    replicas: 2
    replicaExternalLabelName: __replica__
    podMonitorSelector: &selector
      matchLabels: ~
    probeSelector: *selector
    ruleSelector: *selector
    scrapeConfigSelector: *selector
    serviceMonitorSelector: *selector
    enableAdminAPI: true
    walCompression: true
    enableFeatures:
      - auto-gomaxprocs
      - memory-snapshot-on-shutdown
      - new-service-discovery-manager
    thanos:
      image: quay.io/thanos/thanos:v0.36.1
      objectStorageConfig:
        existingSecret:
          name: thanos-objstore-config
          key: config
    retention: 2d
    retentionSize: 15GB
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: ceph-block
          resources:
            requests:
              storage: 20Gi
alertmanager:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: internal
    pathType: Prefix
    hosts:
      - &host alertmanager.cbannister.xyz
    tls:
      - hosts:
          - *host
  alertmanagerSpec:
    replicas: 2
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: ceph-block
          resources:
            requests:
              storage: 10Gi
kubeApiServer:
  serviceMonitor:
    selector:
      k8s-app: kube-apiserver
kubeScheduler:
  service:
    selector:
      k8s-app: kube-scheduler
kubeControllerManager: &kubeControllerManager
  service:
    selector:
      k8s-app: kube-controller-manager
kubeEtcd:
  <<: *kubeControllerManager # etcd runs on control plane nodes
kubeProxy:
  enabled: false
nodeExporter:
  enabled: true
prometheus-node-exporter:
  fullnameOverride: node-exporter
  prometheus:
    monitor:
      enabled: true
      relabelings:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: kubernetes_node
kubeStateMetrics:
  enabled: true
kube-state-metrics:
  fullnameOverride: kube-state-metrics
  metricLabelsAllowlist:
    - pods=[*]
    - deployments=[*]
    - persistentvolumeclaims=[*]
  prometheus:
    monitor:
      enabled: true
      relabelings:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels: ["__meta_kubernetes_pod_node_name"]
          targetLabel: kubernetes_node
grafana:
  enabled: false
  forceDeployDashboards: true
