apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
      containers:
        - name: postgres
          image: postgres:15@sha256:ad126c2b7482bf0ea4f90c2cbb9ab1dfec41ab58d8bef773273a3a1733ad6af0
          securityContext:
            runAsUser: 1001
            runAsNonRoot: true
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /data
          resources:
            limits:
              memory: "4Gi"
              cpu: "2000m"
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /data/pgdata
