apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
commonLabels:
  app: postgres
resources:
  - service.yaml
  - statefulset.yaml
secretGenerator:
  - name: postgres
    literals:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
