apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: postgres-data
spec:
  volumeMode: Filesystem
  storageClassName: smb
  mountOptions:
    - dir_mode=0700
    - file_mode=0700
  resources:
    requests:
      storage: 16Gi
  accessModes:
    - ReadWriteOnce
