apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meshcentral
spec:
  ingressClassName: internal
  rules:
    - host: &host meshcentral.holywoo.cbannister.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: meshcentral
                port:
                  name: http
  tls:
    - hosts:
        - *host
