apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
commonLabels:
  app: meshcentral
resources:
  - deployment.yaml
  - service.yaml
  - volumes.yaml
configMapGenerator:
  - name: meshcentral
    files:
      - config.json=files/config.json
