apiVersion: v1
kind: Service
metadata:
  name: meshcentral
spec:
  selector:
    app: meshcentral
  type: ClusterIP
  ipFamilies:
    - IPv4
  ports:
    - name: http
      port: 80
      targetPort: web
      protocol: TCP
