apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meshcentral-config
spec:
  resources:
    requests:
      storage: 4G
  storageClassName: ceph-block
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
