apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: pg-superuser
    namespace: database
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        # Control destination namespaces
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: default
        # Auto create reflection for matching namespaces
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        # Control auto-reflection namespaces
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: default
stringData:
    username: ENC[AES256_GCM,data:2Ejmw3jk3yo=,iv:oyTSrZ+Ar1IVf1YqeElKiwjm5ThO3Iq2uDnwWH1HGCY=,tag:ep9uGH1tu5D0s2jGtjVl5w==,type:str]
    password: ENC[AES256_GCM,data:yTERkdKCmuAbNeic5u5H+GHYod6pctBRz9JXHnK1,iv:OaebLrLhrqswT/kt1QCZK1oMtnoxaU+EcnTsHdSbqxk=,tag:OsS7OTm0inIxEJU4nltVGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1865axnecqy9eccq9fzhpwkz3nkf0sxfeurva6rquyktplhzssv2s32kv5w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrS0k0M0J6VklrbEdqQ0pw
            czlIMFlJZVhDakVQU05wVjByd1hsNlluVVRzCjNlYUhRN1oxdHRxR1FkVVI5NFl4
            SElydXEvTHp4YUpjYkVMcW13YTQ2MXcKLS0tIDVWcDVoRndWMUdWR1c2TGJkSjdv
            YVJSNFZyZFpwYlJUUGZBMG1uZWtTOVUKqyBg3j4XBmduujjE8eltOffTKrIMGYQ9
            WH1vc8mWjCvrKqlN75gjAoYyPgSk6uc8DMWvH3OVJpDrDfl4XTWuzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-12T12:51:17Z"
    mac: ENC[AES256_GCM,data:8xT68V3CcjNYgW10cDtcS0+0BncNZZPLca8Zv+OGVI44pD8YkDRRJeleRIipPjfKG4VxtDmnpJd+9MsT45UlEhKnidngXg+AuHeYYJwD1T5rkUa6UVnGssFykcpW2CzTdzVsXwkpVcmRJp9pkncRax90FoNQZsFMlD/kuRlnu6M=,iv:V3YqOI70Ugips7T5nAXPIxZigD33tbA3/DzySn4CUo8=,tag:Wpt8SSCmo2PXI+MXykzlbA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
