apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../base
  - ./ingress.yaml
nameSuffix: -main
commonLabels:
  sonarr: main
configMapGenerator:
  - name: sonarr-env-config
    envs:
      - ./config/postgres.env
