apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubernetes-cifs-volumedriver
spec:
  interval: 10m
  url: https://github.com/juliohm1978/kubernetes-cifs-volumedriver.git
  ref:
    branch: master
