apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind
spec:
  selector:
    matchLabels:
      app: bind
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: bind
    spec:
      volumes:
        - name: bind-config
          configMap:
            name: bind-config
        - name: bind-zones
          configMap:
            name: bind-zones
        - name: bind-cache
          persistentVolumeClaim:
            claimName: bind-cache
        - name: zone-files
          emptyDir: {}
      initContainers:
        - name: zone-setup
          image: docker.io/library/alpine:3.19
          command:
            - /bin/sh
            - -c
            - cp -v /etc/bind/zones/* /var/lib/bind
          volumeMounts:
            - mountPath: /etc/bind/zones
              name: bind-zones
            - mountPath: /var/lib/bind
              name: zone-files
        - name: validate-config
          image: docker.io/internetsystemsconsortium/bind9:9.19
          command:
            - /usr/bin/named-checkconf
            - -z
            - /etc/bind/named.conf
          volumeMounts:
            - mountPath: /etc/bind/named.conf
              name: bind-config
              subPath: named.conf
            - mountPath: /etc/bind/externaldns.key
              name: bind-config
              subPath: externaldns.key
            - mountPath: /var/cache/bind
              name: bind-cache
            - mountPath: /var/lib/bind
              name: zone-files
      containers:
        - name: bind
          image: docker.io/internetsystemsconsortium/bind9:9.19
          command:
            - /usr/sbin/named
          args:
            - "-4"
            - -g
            - -c
            - /etc/bind/named.conf
          resources:
            requests:
              memory: &ram "512Mi"
              cpu: "100m"
            limits:
              memory: *ram
          ports:
            - containerPort: 53
              name: dns
              protocol: UDP
          volumeMounts:
            - mountPath: /etc/bind/named.conf
              name: bind-config
              subPath: named.conf
            - mountPath: /etc/bind/externaldns.key
              name: bind-config
              subPath: externaldns.key
            - mountPath: /var/cache/bind
              name: bind-cache
            - mountPath: /var/lib/bind
              name: zone-files
