---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
configMapGenerator:
  - name: bind9-config
    files:
      - named.conf=config/named.conf
      - db.ctb.casa=config/zones/db.ctb.casa
      - externaldns.key=config/externaldns.key
