---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
configMapGenerator:
  - name: bind-config
    files:
      - config/named.conf
      - config/externaldns.key
  - name: bind-zones
    files:
      - config/zones/db.cbannister.xyz
