apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bind-cache2
spec:
  storageClassName: ceph-filesystem
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
