apiVersion: v1
kind: Service
metadata:
  name: bind
spec:
  type: LoadBalancer
  clusterIP: 10.43.53.9
  loadBalancerIP: 192.168.42.55
  selector:
    app: bind
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
