apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../base
  - ./ingress.yaml
nameSuffix: "-1080"
configMapGenerator:
  - name: sonarr-env-config
    envs:
      - ./config/postgres.env
