---
creation_rules:
  - path_regex: k8s/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1865axnecqy9eccq9fzhpwkz3nkf0sxfeurva6rquyktplhzssv2s32kv5w
  - path_regex: k8s/.*\.sops\.(env|ini|json|toml|txt)
    key_groups:
      - age:
          - age1865axnecqy9eccq9fzhpwkz3nkf0sxfeurva6rquyktplhzssv2s32kv5w
  - path_regex: (ansible|terraform)/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1865axnecqy9eccq9fzhpwkz3nkf0sxfeurva6rquyktplhzssv2s32kv5w
  - path_regex: talos/.*\.sops\.yaml$
    key_groups:
      - age:
          - age1865axnecqy9eccq9fzhpwkz3nkf0sxfeurva6rquyktplhzssv2s32kv5w
