apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: cilium
      version: v1.14.0
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 10m
  values:
    namespace: cilium-system
    global:
      kubeProxyReplacement: strict
      containerRuntime:
        integration: containerd
        socketPath: /var/run/k3s/containerd/containerd.sock
