apiVersion: v1
kind: Service
metadata:
  name: pihole-tcp-v4
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole
    external-dns.alpha.kubernetes.io/hostname: pihole.k8s.holywoo.cbannister.xyz
spec:
  selector:
    app: pihole
  type: LoadBalancer
  loadBalancerIP: 10.1.10.42
  externalTrafficPolicy: Local
  ipFamilies:
    - IPv4
  ports:
    - name: http
      port: 80
      targetPort: web
      protocol: TCP
    - name: dns
      port: 53
      targetPort: 53
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-udp-v4
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole
spec:
  selector:
    app: pihole
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 10.1.10.42
  ipFamilies:
    - IPv4
  ports:
    - name: dns
      port: 53
      targetPort: 53
      protocol: UDP
