apiVersion: v1
kind: Service
metadata:
  name: pihole-tcp-v4
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole
spec:
  selector:
    app: pihole
  type: LoadBalancer
  loadBalancerIP: 10.1.10.42
  ipFamilies:
    - IPv4
  ports:
    - name: http
      port: 80
      targetPort: web
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-udp-v4
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole
spec:
  selector:
    app: pihole
  type: LoadBalancer
  loadBalancerIP: 10.1.10.42
  ipFamilies:
    - IPv4
  ports:
    - name: http
      port: 53
      targetPort: dns
      protocol: UDP
