cluster:
  name: default
ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDRList: 10.42.0.0/16
k8sServiceHost: 10.100.0.10
k8sServicePort: 6443
kubeProxyReplacement: strict
operator:
  replicas: 1
serviceAccounts:
  cilium:
    name: cilium
  operator:
    name: cilium-operator
tunnel: vxlan
