machine:
  kubelet:
    extraArgs:
      image-gc-high-threshold: "55"
      image-gc-low-threshold: "50"
      rotate-server-certificates: "true"
    nodeIP:
      validSubnets:
        - 192.168.42.0/24

  install:
    disk: /dev/sda # The disk used for installations.

    diskSelector:
      size: "< 800GB"

    extraKernelArgs:
      - mitigations=off

  features:
    kubePrism:
      enabled: true
      port: 7445

cluster:
  network:
    podSubnets:
      - 10.42.0.0/16
    serviceSubnets:
      - 10.43.0.0/16
    cni:
      name: none
  proxy:
    disabled: true
