apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: static-config
  labels:
    prometheus: system-monitoring-prometheus
spec:
  staticConfigs:
    - targets:
        - gateway.cbannister.casa:9100
  metricsPath: /metrics
