all:
  vars:
    ansible_user: chris
k8s:
  vars:
    nvidia_gpu: false
    vlan: false
    vlan_id: 42
  children:
    control_plane:
      vars:
        matchbox_profile: talos-control
      hosts:
        k8s-0:
          mac_addr: ec:8e:b5:70:ca:20
        k8s-1:
          mac_addr: 48:21:0b:60:1a:3f
        k8s-2:
          mac_addr: ec:8e:b5:70:f6:59
    worker:
      hosts:
        k8s-3:
          matchbox_profile: talos-k8s-3
          mac_addr: f6:45:04:c6:96:e0 # mellanox
          pxe_mac_addr: bc:24:11:da:2b:0a # pve
        k8s-4:
          matchbox_profile: talos-k8s-4
          mac_addr: 48:21:0b:56:ac:6c
ungrouped:
  hosts:
    vyos:
      ansible_host: 10.1.2.1
      ansible_user: vyos
