---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: &email c.bannister@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: *email
            apiTokenSecretRef:
              name: certmanager-cloudflare
              key: api-key
        selector:
          dnsZones:
            - cbannister.xyz
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: &email c.bannister@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email: *email
            apiTokenSecretRef:
              name: certmanager-cloudflare
              key: api-key
        selector:
          dnsZones:
            - cbannister.xyz
