---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  PYTHON_BIN: python3

env:
  PATH: "{{.ROOT_DIR}}/.venv/bin:$PATH"
  VIRTUAL_ENV: "{{.ROOT_DIR}}/.venv"
  ANSIBLE_COLLECTIONS_PATH: "{{.ROOT_DIR}}/.venv/galaxy"
  ANSIBLE_ROLES_PATH: "{{.ROOT_DIR}}/.venv/galaxy/ansible_roles"
  ANSIBLE_VARS_ENABLED: "host_group_vars"

tasks:
  venv:
    desc: Set up Python virtual environment
    cmds:
      - true && {{.PYTHON_BIN}} -m venv {{.ROOT_DIR}}/.venv
      - .venv/bin/python3 -m pip install --upgrade pip setuptools wheel
      - .venv/bin/python3 -m pip install --upgrade --requirement {{.ANSIBLE_DIR}}/requirements.txt
      - .venv/bin/ansible-galaxy install --role-file "{{.ANSIBLE_DIR}}/requirements.yaml" --force
    sources:
      - "{{.ANSIBLE_DIR}}/requirements.txt"
      - "{{.ANSIBLE_DIR}}/requirements.yaml"
    generates:
      - "{{.ROOT_DIR}}/.venv/pyvenv.cfg"

  run:
    desc: Run an Ansible playbook for configuring a cluster
    summary: |
      Args:
        cluster: Cluster to run command against (required)
        playbook: Playbook to run (required)
    cmd: |
      .venv/bin/ansible-playbook \
        --inventory {{.ANSIBLE_DIR}}/main/inventory/hosts.yaml \
        {{.ANSIBLE_DIR}}/main/playbooks/{{.playbook}}.yaml {{.CLI_ARGS}}
    requires:
      vars: ["playbook"]
    preconditions:
      - test -d {{.ROOT_DIR}}/.venv
      - test -f {{.ANSIBLE_DIR}}/main/inventory/hosts.yaml
      - test -f {{.ANSIBLE_DIR}}/main/playbooks/{{.playbook}}.yaml

  init:
    desc: Run the init playbook on a specific host
    cmd: |
      .venv/bin/ansible-playbook \
        -i {{.host}}, -kK --become-method=ansible.builtin.su \
        {{.ANSIBLE_DIR}}/common/playbooks/node-init.yaml {{.CLI_ARGS}}
    requires:
      vars: ["host"]
    preconditions:
      - test -d {{.ROOT_DIR}}/.venv
