apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: golinks-data
  labels:
    app: golinks
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: golinks
  labels:
    app: golinks
spec:
  selector:
    matchLabels:
      app: golinks
  template:
    metadata:
      labels:
        app: golinks
    spec:
      volumes:
        - name: golinks-data
          persistentVolumeClaim:
            claimName: golinks-data
      containers:
        - name: golinks
          image: ghcr.io/tailscale/golink:main@sha256:82c85d3fda1871420d4cb1cd47c8d3f048af7215939e33239ee7f72e47cb8621
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: golinks-data
              mountPath: /home/nonroot
          # livenessProbe:
          #   httpGet:
          #     path: /api/v1/health
          #     port: web
          #   initialDelaySeconds: 10
          #   periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: golinks
  name: golinks
spec:
  selector:
    app: golinks
  type: LoadBalancer
  loadBalancerIP: 10.1.13.2
  ports:
    - name: http
      port: 80
      targetPort: web
      protocol: TCP
