apiVersion: v1
kind: Service
metadata:
  labels:
    app: sabnzbd
  name: sabnzbd-v4
  annotations:
    external-dns.alpha.kubernetes.io/hostname: sabnzbd.k8s.holywoo.cbannister.xyz
spec:
  selector:
    app: sabnzbd
  type: LoadBalancer
  loadBalancerIP: 10.1.12.5
  ipFamilies:
    - IPv4
  ports:
    - name: http
      port: 80
      targetPort: web
      protocol: TCP
