apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cbannister-xyz
  namespace: network
spec:
  secretName: cbannister-xyz-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: cbannister.xyz
  dnsNames:
    - cbannister.xyz
    - "*.cbannister.xyz"
