---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
labels:
  - pairs:
      app.kubernetes.io/name: cloudflared
resources:
  - dnsendpoint.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
configMapGenerator:
  - name: cloudflared-config
    files:
      - ./config/config.yaml
secretGenerator:
  - name: cloudflared-tunnel-secret
    type: Opaque
    files:
      - ./config/credentials.sops.json
