apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale-subnet-router
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["secrets"]
    # Create can not be restricted to a resource name.
    verbs: ["create"]
  - apiGroups: [""] # "" indicates the core API group
    resourceNames: ["tailscale-state"]
    resources: ["secrets"]
    verbs: ["get", "update", "patch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale-subnet-router
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale-subnet-router
subjects:
  - kind: ServiceAccount
    name: tailscale-subnet-router
roleRef:
  kind: Role
  name: tailscale-subnet-router
  apiGroup: rbac.authorization.k8s.io
