apiVersion: apps/v1
kind: Deployment
metadata:
  name: glauth
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app.kubernetes.io/component: glauth
    app.kubernetes.io/instance: glauth
    app.kubernetes.io/name: glauth
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/component: glauth
      app.kubernetes.io/instance: glauth
      app.kubernetes.io/name: glauth
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: glauth
        app.kubernetes.io/instance: glauth
        app.kubernetes.io/name: glauth
    spec:
      automountServiceAccountToken: true
      containers:
        - name: glauth
          command:
            - /app/glauth
            - -c
            - /config
          image: docker.io/glauth/glauth:v2.3.2@sha256:5112abbb2b5145dadb1a2fed57242ad3718e4af11062d0bb812b50cda6c708ab
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 5555
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 5555
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /config/groups.toml
              name: config
              readOnly: true
              subPath: groups.toml
            - mountPath: /config/server.toml
              name: config
              readOnly: true
              subPath: server.toml
            - mountPath: /config/users.toml
              name: config
              readOnly: true
              subPath: users.toml
      restartPolicy: Always
      securityContext:
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: glauth
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
      volumes:
        - name: config
          secret:
            defaultMode: 420
            secretName: glauth-secret
