---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: media
provisioner: nfs
parameters:
  archiveOnDelete: "false"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bighorse-arr-media
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: media
  capacity:
    storage: 1000Gi
  nfs:
    server: truenas.holywoo.cbannister.xyz
    path: /mnt/bighorse/arr
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - hard
    - noatime
    - rsize=131072
    - wsize=131072
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bighorse-arr-media
spec:
  volumeMode: Filesystem
  volumeName: bighorse-arr-media
  storageClassName: media
  resources:
    requests:
      storage: 1000Gi
  accessModes:
    - ReadWriteMany
