apiVersion: v1
kind: PersistentVolume
metadata:
  name: horsepc-sabnzbd-complete
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb-horsepc
  capacity:
    storage: 100Gi
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=568
    - gid=568
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino # required to prevent data corruption
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    # volumeHandle format: {smb-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: horsepc#sabnzbd-complete
    volumeAttributes:
      source: //horsepc/sabnzbd-complete
    nodeStageSecretRef:
      name: smb-horsepc
      namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: horsepc-sabnzbd-complete
spec:
  volumeMode: Filesystem
  volumeName: horsepc-sabnzbd-complete
  storageClassName: smb-horsepc
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany
