# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./lidarr/ks.yaml
  - ./plex/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml
  - ./storage
  - ./jellyfin/ks.yaml
  - ./tautulli/ks.yaml
  - ./secrets
  - ./smtp-relay/ks.yaml
  - miniflux/ks.yaml
  - overseerr/ks.yaml
  - atuin/ks.yaml
  - qbittorrent/ks.yaml
  - autobrr/ks.yaml
  - omegabrr/ks.yaml
  - flaresolverr/ks.yaml
  - cross-seed/ks.yaml
  - unpackerr/ks.yaml
