apiVersion: v1
kind: Service
metadata:
  name: prowlarr-v4
  annotations:
    external-dns.alpha.kubernetes.io/hostname: prowlarr.k8s.holywoo.cbannister.xyz
spec:
  selector:
    app: prowlarr
  type: LoadBalancer
  loadBalancerIP: 10.1.12.2
  ipFamilies:
    - IPv4
  ports:
    - name: http
      port: 80
      targetPort: web
      protocol: TCP
