---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-kube-prometheus-stack
  namespace: flux-system
spec:
  path: ./k8s/apps/monitoring/kube-prometheus-stack/app
  dependsOn:
    - name: cluster-apps-rook-ceph-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-kube-prometheus-stack-monitors
  namespace: flux-system
spec:
  path: ./k8s/apps/monitoring/kube-prometheus-stack/monitors
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: cluster-apps-kube-prometheus-stack
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 15m
