apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: default
spec:
  interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: pihole-values
  chart:
    spec:
      chart: pihole
      version: 2.11.1
      sourceRef:
        kind: HelmRepository
        name: pihole
