kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: autobrr-config
spec:
  storageClassName: ceph-filesystem
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
