apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  labels:
    app: radarr
spec:
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      hostname: radarr
      volumes:
        - name: arr-media
          persistentVolumeClaim:
            claimName: bighorse-arr-media
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        runAsNonRoot: true
      containers:
        - name: radarr
          image: ghcr.io/onedr0p/radarr-develop:rolling@sha256:f62b8d569fafe0068755c1e080c17646fba7829c19c860a34679e7a7a1178227
          imagePullPolicy: "IfNotPresent"
          env:
            - name: DOTNET_EnableDiagnostics
              value: "0"
            - name: DOTNET_gcServer
              value: "1"
            - name: RADARR__POSTGRES_HOST
              value: postgres
            - name: RADARR__POSTGRES_MAIN_DB
              value: radarr-main
            - name: RADARR__POSTGRES_LOG_DB
              value: radarr-logs
            - name: RADARR__POSTGRES_USER
              value: holywoo
            - name: RADARR__POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: 8192Mi
              cpu: 4000m
          ports:
            - containerPort: 7878
              name: web
          volumeMounts:
            - name: arr-media
              mountPath: /data
          startupProbe:
            httpGet:
              path: /ping
              port: web
            failureThreshold: 6
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ping
              port: web
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
