apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
spec:
  type: oci
  interval: 5m
  url: oci://ghcr.io/prometheus-community/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 5m
  targetNamespace: monitoring
  releaseName: kube-prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 48.4.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 30m
  valuesFrom:
    - kind: ConfigMap
      name: kube-prometheus-stack-values
