apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  labels:
    app: radarr
spec:
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: ghcr.io/onedr0p/radarr:rolling@sha256:d92c1aeb857aab4ed9d3de9fcd880b332b2d1fb5603b8e322ea24400bc393599
          imagePullPolicy: "IfNotPresent"
          env:
            - name: COMPlus_EnableDiagnostics
              value: "0"
          securityContext:
            runAsUser: 568
            runAsNonRoot: true
            readOnlyRootFilesystem: true
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 7878
              name: web
          livenessProbe:
            httpGet:
              path: /ping
              port: web
            initialDelaySeconds: 10
            periodSeconds: 20
