apiVersion: v1
kind: Service
metadata:
  labels:
    app: radarr
  name: radarr-v4
spec:
  selector:
    app: radarr
  type: LoadBalancer
  loadBalancerIP: 10.1.12.3
  ipFamilies:
    - IPv4
  ports:
    - name: http
      port: 80
      targetPort: 7878
      protocol: TCP
