apiVersion: apps/v1
kind: Deployment
metadata:
  name: recyclarr
spec:
  selector:
    matchLabels:
      app: recyclarr
  template:
    metadata:
      labels:
        app: recyclarr
    spec:
      hostname: recyclarr
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: recyclarr-config
        - name: recyclarr-yml
          configMap:
            name: recyclarr-config
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        runAsNonRoot: true
      containers:
        - name: recyclarr
          image: ghcr.io/recyclarr/recyclarr:latest@sha256:ede628bd5a3064cc9299db23da3c3c7d99417cdae0fe31fdbe04daf9971edd57
          imagePullPolicy: IfNotPresent
          env:
            - name: DOTNET_EnableDiagnostics
              value: "0"
            - name: DOTNET_gcServer
              value: "1"
          resources:
            requests:
              memory: 50Mi
              cpu: 10m
            limits:
              memory: 200Mi
              cpu: 500m
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: false
            - name: recyclarr-yml
              subPath: recyclarr.yml
              mountPath: /config/recyclarr.yml
              readOnly: true
