apiVersion: apps/v1
kind: Deployment
metadata:
  name: recyclarr
spec:
  selector:
    matchLabels:
      app: recyclarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: recyclarr
    spec:
      hostname: recyclarr
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: recyclarr-config
        - name: recyclarr-yml
          configMap:
            name: recyclarr-config
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        runAsNonRoot: true
      containers:
        - &container
          name: recyclarr
          image: ghcr.io/recyclarr/recyclarr:latest@sha256:a8348500d3e113eac448e42874b482eff46891b69e613e2d06fdb8fa922a4c1f
          imagePullPolicy: IfNotPresent
          env:
            - name: DOTNET_EnableDiagnostics
              value: "0"
            - name: DOTNET_gcServer
              value: "1"
          resources:
            requests:
              memory: 200Mi
              cpu: 10m
            limits:
              memory: 200Mi
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: false
            - name: recyclarr-yml
              subPath: recyclarr.yml
              mountPath: /config/recyclarr.yml
              readOnly: true
      initContainers:
        - <<: *container
          name: recyclarr-sync
          args:
            - sync
