apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
commonLabels:
  app: recyclarr
resources:
  - deployment.yaml
  - pvc.yaml
configMapGenerator:
  - name: recyclarr-config
    files:
      - config/recyclarr.yaml
      - config/sonarr.yaml
