apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
commonLabels:
  app: recyclarr
resources:
  - deployment.yaml
configMapGenerator:
  - name: recyclarr-config
    files:
      - recyclarr.yml=config/recyclarr.yaml
