apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recyclarr-config
spec:
  storageClassName: bighorse-nfs
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
