apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name omegabrr
  labels:
    app: *name
spec:
  selector:
    matchLabels:
      app: *name
  template:
    metadata:
      labels:
        app: *name
    spec:
      hostname: *name
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [10000]
        seccompProfile: { type: RuntimeDefault } 
      volumes:
        - name: config
          configMap:
            name: omegabrr-config
      containers:
        - name: *name
          image: ghcr.io/autobrr/omegabrr:v1.14.0
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Europe/London
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: { drop: ["ALL"] }
          ports:
            - containerPort: 80
              name: web
          resources:
            requests:
              cpu: 100m
            limits:
              memory: 256Mi
          volumeMounts:
            - name: config
              mountPath: /config/config.yaml
              subPath: config.yaml
              readOnly: true
