apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - clustersecretstore.yaml
secretGenerator:
  - name: onepassword-connect-secret
    files:
      - onepassword-credentials.json=config/onepassword-credentials.sops.json
      - token=config/token.sops.txt
configurations:
  - kustomizeconfig.yaml
