ipv4_cluster_cidr: 10.32.0.0/16

k3s_control_node: true
k3s_etcd_datastore: true
k3s_server:
  tls-san:
    - "{{ k3s_registration_address }}"
  https-listen-port: 6443
  docker: false
  flannel-backend: "none" # quote
  disable:
    - coredns
    - flannel
    - local-storage
    - metrics-server
    - servicelb
    - traefik
  disable-network-policy: true
  disable-cloud-controller: true
  disable-kube-proxy: true
  cluster-cidr: "{{ ipv4_cluster_cidr }},{{ ipv6_cluster_cidr }}"
  service-cidr: "10.33.0.0/16,{{ ipv6_service_cidr }}"
  node-ip: "{{ ansible_host }},{{ ipv6 }}"
  write-kubeconfig-mode: "0644"
  etcd-expose-metrics: true
  kube-controller-manager-arg:
    - bind-address=0.0.0.0
    - node-cidr-mask-size-ipv6=112
    - node-cidr-mask-size-ipv4=24
    - allocate-node-cidrs
  kube-scheduler-arg:
    - bind-address=0.0.0.0
  kube-apiserver-arg:
    - anonymous-auth=true
