apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-db
spec:
  storageClassName: bighorse-nfs
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
