apiVersion: v1
kind: Service
metadata:
  name: pihole-v4
  annotations:
    external-dns.alpha.kubernetes.io/hostname: pihole.k8s.holywoo.cbannister.xyz
spec:
  selector:
    app: pihole
  type: LoadBalancer
  loadBalancerIP: 10.1.10.42
  ipFamilies:
    - IPv4
  ports:
    - name: http
      port: 80
      targetPort: web
      protocol: TCP
    - name: dns
      port: 53
      targetPort: 53
      protocol: UDP
