apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: csi-drvier-smb
spec:
  interval: 10m
  url: https://github.com/kubernetes-csi/csi-driver-smb.git
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include
    !/deploy/**/*.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: csi-drvier-smb
spec:
  interval: 10m
  targetNamespace: kube-system
  sourceRef:
    kind: GitRepository
    name: csi-drvier-smb
  path: "/deploy/v1.11.0"
  prune: true
  timeout: 1m
