apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
spec:
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      volumes:
        - name: prowlar-backups
          emptyDir: {}
        - name: tmp
          emptyDir: {}
      containers:
        - name: prowlarr
          image: ghcr.io/onedr0p/prowlarr-develop:rolling@sha256:461c5440e4aa0e0dbaa883db71cb5529fcaed84f0e2c793ccd8d4029c7782873
          imagePullPolicy: "IfNotPresent"
          env:
            - name: COMPlus_EnableDiagnostics
              value: "0"
          securityContext:
            runAsUser: 568
            runAsNonRoot: true
            readOnlyRootFilesystem: true
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 9696
              name: web
          volumeMounts:
            - name: prowlar-backups
              mountPath: /tmp/prowlarr_backup
            - name: tmp
              mountPath: /tmp
          livenessProbe:
            httpGet:
              path: /ping
              port: web
            initialDelaySeconds: 10
            periodSeconds: 20
