apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
commonLabels:
  app: prowlarr
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: prowlarr-config
    files:
      - config.xml=files/config.xml
