apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: prowlarr-config
spec:
  volumeMode: Filesystem
  storageClassName: smb
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
