apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name blocky
spec:
  selector:
    matchLabels:
      app: *name
  replicas: 2
  template:
    metadata:
      labels:
        app: *name
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: *name
      volumes:
        - name: blocky-config
          configMap:
            name: blocky-config
      containers:
        - name: blocky
          image: ghcr.io/0xerr0r/blocky:v0.23
          env:
            - name: TZ
              value: Europe/London
          resources:
            requests:
              memory: &ram "512Mi"
              cpu: "100m"
            limits:
              memory: *ram
          ports:
            - containerPort: 53
              name: dns
              protocol: UDP
            - containerPort: 4000
              name: metrics
              protocol: TCP
          volumeMounts:
            - mountPath: /app/config.yml
              name: blocky-config
              subPath: config.yml
          livenessProbe: &probe
            exec:
              command:
                - /app/blocky
                - healthcheck
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe: *probe
