apiVersion: v1
kind: Service
metadata:
  name: blocky
spec:
  type: LoadBalancer
  clusterIP: 10.43.53.10
  loadBalancerIP: 192.168.42.56
  selector:
    app: blocky
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns-udp
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dns-tcp
