apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-sharing-bighorse
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb-bighorse
  capacity:
    storage: 1000Gi
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=568
    - gid=568
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino # required to prevent data corruption
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    # volumeHandle format: {smb-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: bighorse#sharing
    volumeAttributes:
      source: //192.168.42.32/sharing
    nodeStageSecretRef:
      name: smb-bighorse
      namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-sharing-bighorse
spec:
  volumeMode: Filesystem
  volumeName: nas-sharing-bighorse
  storageClassName: smb-bighorse
  resources:
    requests:
      storage: 1000Gi
  accessModes:
    - ReadWriteOnce
