apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - deployment.yaml
  - service.yaml
  - volume.yaml
  - externalsecret.yaml
commonLabels:
  app.kubernetes.io/part-of: radarr
configMapGenerator:
  - name: radarr-env-config
    envs:
      - ./config/postgres.env
