apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: reflector
spec:
  interval: 30m
  targetNamespace: kube-system
  releaseName: reflector
  chart:
    spec:
      chart: reflector
      version: 7.1.262
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
