apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reflector
spec:
  interval: 30m
  targetNamespace: kube-system
  releaseName: reflector
  chart:
    spec:
      chart: reflector
      version: 1.14.2
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
