apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controller:
      type: statefulset
    image:
      repository: ghcr.io/onedr0p/home-assistant
      tag: rolling@sha256:64a5793ebba62c989de4e721f987a05cba7b2705271a9f9da1e6fc1cfe9f9357
    env:
      TZ: Europe/London
      HASS_POSTGRES_URL: "postgresql://holywoo:horse@postgres.holywoo.cbannister.xyz/home-assistant"
      HASS_LATITUDE: "51.505150"
      HASS_LONGITUDE: "0.042130"
      HASS_ELEVATION: 0
    service:
      main:
        ports:
          http:
            port: 8123
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: hass.holywoo.cbannister.xyz
            paths:
              - path: /
                pathType: Prefix
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 5Gi
        storageClass: ceph-block
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 750Mi
