apiVersion: apps/v1
kind: Deployment
metadata:
  name: recyclarr
spec:
  selector:
    matchLabels:
      app: recyclarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: recyclarr
    spec:
      hostname: recyclarr
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: recyclarr-config
        - name: recyclarr-configs
          secret:
            secretName: recyclarr-secret
        - name: recyclarr-includes
          configMap:
            name: recyclarr-includes
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        runAsNonRoot: true
      containers:
        - &container
          name: recyclarr
          image: ghcr.io/recyclarr/recyclarr:7.2.4
          imagePullPolicy: IfNotPresent
          env:
            - name: DOTNET_EnableDiagnostics
              value: "0"
            - name: DOTNET_gcServer
              value: "1"
          resources:
            requests:
              memory: 200Mi
              cpu: 10m
            limits:
              memory: 200Mi
          volumeMounts:
            - name: config
              mountPath: /config/
              readOnly: false
            - name: recyclarr-configs
              mountPath: /config/configs
              readOnly: true
            - name: recyclarr-includes
              mountPath: /config/includes
              readOnly: true
      initContainers:
        - <<: *container
          name: recyclarr-sync
          args:
            - sync
