---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: recyclarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: recyclarr-secret
    template:
      engineVersion: v2
      data: 
        recyclarr.yaml: |
          sonarr:
            sonarr-main:
              base_url: http://sonarr-main.default.svc.cluster.local
              api_key: {{ .SONARR_API_KEY }}
              include:
                - config: sonarr.yaml
            sonarr-1080:
              base_url: http://sonarr-1080.default.svc.cluster.local
              api_key: {{ .SONARR_API_KEY }}
              include:
                - config: sonarr.yaml
          radarr:
            radarr-main:
              base_url: http://radarr-main.default.svc.cluster.local
              api_key: {{ .RADARR_API_KEY }}
              include:
                - config: radarr.yaml
            radarr-1080:
              base_url: http://radarr-1080p.default.svc.cluster.local
              api_key: {{ .RADARR_API_KEY }}
              include:
                - config: radarr.yaml
  dataFrom:
    - extract:
        key: radarr
    - extract:
        key: sonarr
