apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
commonLabels:
  app: recyclarr
resources:
  - deployment.yaml
  - pvc.yaml
configMapGenerator:
  - name: recyclarr-config
    files:
      - recyclarr.yaml=config/recyclarr.yaml
      - sonarr.yaml=config/sonarr.yaml
      - radarr.yaml=config/radarr.yaml
