apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recyclarr-config
spec:
  storageClassName: ceph-fileystem
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
