apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: metallb
spec:
  interval: 60m
  sourceRef:
    kind: GitRepository
    name: metallb
  path: "config/manifests/metallb-native.yaml"
  prune: true
