apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
spec:
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
      volumes:
        - name: transcode
          emptyDir: {}
        - name: config
          persistentVolumeClaim:
            claimName: plex-config
        - name: arr-media
          persistentVolumeClaim:
            claimName: bighorse-arr-media
            readOnly: true
      containers:
        - name: plex
          image: ghcr.io/onedr0p/plex-beta:rolling@sha256:437685fa85bee0731f36610b473b807aad436ca2408815018002206f9abf6fe6
          env:
            - name: TZ
              value: Europe/London
            - name: ADVERTISE_IP
              value: "http://plex.k8s.holywoo.cbannister.xyz:32400/"
          resources:
            limits:
              memory: "8096Mi"
              cpu: "4000m"
          ports:
            - containerPort: 32400
              name: web
          volumeMounts:
            - name: transcode
              mountPath: /transcode
            - name: config
              mountPath: /config
            - name: arr-media
              mountPath: /data
