apiVersion: v1
kind: Service
metadata:
  name: plex
  annotations:
    external-dns.alpha.kubernetes.io/hostname: plex.holywoo.cbannister.xyz
spec:
  selector:
    app: plex
  type: LoadBalancer
  LoadBalancerIP: 192.168.42.203
  ipFamilies:
    - IPv4
  ports:
    - name: http
      port: 80
      targetPort: web
      protocol: TCP
