apiVersion: v1
kind: Service
metadata:
  name: plex
spec:
  selector:
    app: plex
  type: ClusterIP
  ipFamilies:
    - IPv4
  ports:
    - name: http
      port: 80
      targetPort: web
      protocol: TCP
