apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-local
spec:
  storageClassName: local-path
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
