apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: local
spec:
  avoidBuggyIPs: true
  addresses:
    - 10.1.0.0/16
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: local
spec:
  ipAddressPools:
    - local
