---
originRequest:
  originServerName: external.devbu.io

ingress:
  - hostname: cbannister.xyz
    service: https://nginx-external-controller.network.svc.cluster.local:443
  - hostname: "*.cbannister.xyz"
    service: https://nginx-external-controller.network.svc.cluster.local:443
  - service: http_status:404
