apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium/ks.yaml
  - csi-driver-smb/ks.yaml
  - nfs-provisioner
  - metrics-server
  - descheduler
  - reflector
  - spegel/ks.yaml
  - kubelet-csr-approver/ks.yaml
  - coredns/ks.yaml
  - fstrim/ks.yaml
  - reloader/ks.yaml
