apiVersion: apps/v1
kind: Deployment
metadata:
  name: lldap
spec:
  selector:
    matchLabels:
      app: lldap
  replicas: 2
  template:
    metadata:
      labels:
        app: lldap
    spec:
      volumes:
        - name: data
          emptyDir: {}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: lldap
      initContainers:
        - name: init-db
          image: ghcr.io/onedr0p/postgres-init:14.9
          imagePullPolicy: IfNotPresent
          env:
            - name: INIT_POSTGRES_SUPER_PASS
              valueFrom:
                secretKeyRef:
                  name: pg-holywoo
                  key: password
            - name: INIT_POSTGRES_SUPER_USER
              valueFrom:
                secretKeyRef:
                  name: pg-holywoo
                  key: username
          envFrom: &envFrom
            - secretRef:
                name: lldap-secret
      containers:
        - name: lldap
          image: ghcr.io/lldap/lldap:v0.5.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "5m"
              memory: "36Mi"
            limits:
              memory: "128Mi"
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 389
              name: ldap
              protocol: TCP
          env:
            - name: TZ
              value: Europe/London
            - name: LLDAP_HTTP_PORT
              value: "80"
            - name: LLDAP_HTTP_URL
              value: https://lldap.holywoo.cbannister.xyz
            - name: LLDAP_LDAP_PORT
              value: "389"
            - name: LLDAP_LDAP_BASE_DN
              value: dc=home,dc=arpa
            - name: LLDAP_DATABASE_URL
              value: "postgres://${INIT_POSTGRES_USER}:${INIT_POSTGRES_PASS}}@postgres-rw.database.svc.cluster.local/lldap"
          envFrom: *envFrom
          volumeMounts:
            - mountPath: /data
              name: data
