apiVersion: v1
kind: Secret
metadata:
    name: lldap-secret
type: Opaque
stringData:
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:StIN+DbpgUzxwxRJOb4lDTLCZx36lE7Em2XU9unnvW8=,iv:TC5RZ+ZNxe4MmpZiz+r7rH4GwsA+mYw5THOz7angg6s=,tag:QMvb76AGJQl9RszwUdk/mA==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:8w1T2xPmHfKU9qQNQhoi1IH5OZHvb8DCWcg93+uV7SA=,iv:kwh8XmN1DW4jrbfKPXtTbp4xzsa8BYmZo/9zjstm9+I=,tag:EbLsOU9j7Pc91NMtnc5zEQ==,type:str]
    LLDAP_USER_DN: ENC[AES256_GCM,data:ULxBOgU=,iv:1IzdY90Gt29Bcog6nu+QQw4l2mRom7ueSomlJ2GAuaY=,tag:SAIzA4gzmKIHbeliR8Bwdw==,type:str]
    LLDAP_LDAP_USER_EMAIL: ENC[AES256_GCM,data:CSloeOHdTSJPH8cX6Zot07uVTidU,iv:ZvHxtkvzkHAmMx66hdTxDmM4BDYSyXQWWsIcR1RxCDU=,tag:iaRglP+o5E1zqXucxsGwYQ==,type:str]
    LLDAP_SERVER_KEY_SEED: ENC[AES256_GCM,data:OAy5Tk0kSiqGi1aTdbbl+xwPTA2+D997rm242VHSILkTHSY/lhkUjFS005GhVmwEVpI8DkGqpnid/16DQyCyzg==,iv:hUoqqSBFGovn9kZ7oLF+RtNlpnbh/3IvYUg/+FOD9NU=,tag:QI7Edio6cCQeAxMItFR5pg==,type:str]
    #ENC[AES256_GCM,data:R6e9l9x170Aoim66+3Y=,iv:yV2Z6D/H6KFwHKuDdie6/864p3bNeZFKFuqP4GiHmho=,tag:EG3BdNdhfsiVS3xpoUwdPQ==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:nvPtMa0=,iv:Z0+Hg2VcCCQu/qF7N7p2Ba/7bNZxDnEvQWH/uarKhPw=,tag:QgAs/l6TgDSUcdFN9eLoFQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:7NCgXqZKl5gst2G+ywNXmxo3AlsQFv5dPKhdD7RcCP0+lg7UsxE=,iv:u9OiIZ3/JcWB78uM3e7N6wQ6zOc7qGo3/blT31lNjVQ=,tag:kPejpB06N/gqR/Fq5yNMGg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:G6PWofQ=,iv:D8Sh8D7hqM+6Na+lVMv5jcq/mMt3xMycbeea4RwXjHs=,tag:GhneD6qbHwfHtuG+Pqb8wA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:WKSEZIh2U+75jtpJl2zKpYJRY4nqaNZhy19ZGyc+iDg=,iv:O0/gDTsz+IUH/N1PqC2swQpj6gjI9JMe5Qbulbr+hno=,tag:QfAaxIdGW3XMh8CJdhTA4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1865axnecqy9eccq9fzhpwkz3nkf0sxfeurva6rquyktplhzssv2s32kv5w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVT0dZR3VCZzR4ek9EMUxl
            UnIrOTVsMU9qMGk1aXpSbjNtZEJSSm5abEFBClJ6S0U5Y0V6QVNwNndWNEhnam9h
            MnlaVGU3R3pjelZvTEJIUWttcm5TY2cKLS0tIGpIS09Jc1JvdUFmTnBWNnJCSU9E
            N3Rja0RoeEFrcWJmRE5YLzlxbVJuNVUK1H/vvC4YX4QNREmvpYfYKDJqy4lac148
            NmweaXY4q7fZpyJGYpg5gEaxUHpXVi2Ksqte0kTam3f8wVeDgo+eJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-12T12:06:37Z"
    mac: ENC[AES256_GCM,data:2inPcnPKTJs6ozInPKGRowl5yIo4eTEc7nXaApERNXyrOfhROmlzf/1R167K9DoNcQRbhzpGviCEv3Gds29v9bl0GkttobELFItHeeeMWYIdTDh1fQQloKGRzdKugBVe74IV1jI1xj3K4fPUy0zuWpeklzUnb7QrpbfxXzBLb/s=,iv:/nP50LsCy9Wq19dcSfAJhm4PwZ7IG55XagSjWfLkF6k=,tag:akOFPGX7w+hxzIU/rdmtYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
