apiVersion: v1
kind: Secret
metadata:
    name: lldap-secret
type: Opaque
stringData:
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:VK94xf+KZ9ti5jtSDvSinOJWTa2/3IbOTVCL2eyC2NI=,iv:E9SByAHa3mna0Cr0Jo7Ilj49tLA7ahHw1ORroMYByHA=,tag:CWC2oJXR2XT1QUBXrSM3lQ==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:8GKIpyGeqvQhfgMcZbhaXxR9QFjjRCVjSBQoEfTMDs0=,iv:M73moRcF/D1kB8vPaoDGMyyTkHv8oRftyZ0Y+pXdDRc=,tag:G6+oRIV/QtVctLZcmFJejQ==,type:str]
    LLDAP_USER_DN: ENC[AES256_GCM,data:BP6cxME=,iv:s506aL5S1QTUNu+m01FNkcaBNCh75Z/Qr2Sb2zyhoiU=,tag:Uc1qVLfz5QGDHaXpXmDhdQ==,type:str]
    LLDAP_LDAP_USER_EMAIL: ENC[AES256_GCM,data:njAkMJulcXrTT4Ie+miYOUx9xwMQ,iv:gk8PuP5dEqoZFJ3BH5WyhwokpojFpQMOEqDScUZKPHw=,tag:gc+vveobAxJk4f9EC9eiYw==,type:str]
    LLDAP_SERVER_KEY_SEED: ENC[AES256_GCM,data:5P8bNFEc+Bl09l1ZDPO4CjghdPCnwx2bAIt8wO2muDVQA1Ypb0SXt+lBHb2g7kWmjldCx/Q1vWIR0PY78l2Qow==,iv:ZMNEnV2t3u9dpx3xbCt2HR8lMT7CC63tceGKmu/Fbg4=,tag:8qgeaYYmKoAEuv6kAx8aTw==,type:str]
    #ENC[AES256_GCM,data:/6PsJ6Usy7hMM/PbUT8=,iv:C8eMhqfN9m6rl95unweF5r04xMf5ovfN74HXPhlNpWs=,tag:fE47b6FrtjasCJK3cbVdQw==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:6vs2kLc=,iv:UJ+CQMjqjy2gfs5/TZA27SEWQJPmQmFBPYooBSpe4cg=,tag:k0NaVeMBlqg+Cg/Yoa9AyQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:KND0nAQCw/oFNfPlVsIl/EMKcJVVdtqX68EgUhtR0AGANc//3EE=,iv:n04WZNgrnBB3mCGVHfdPr3eDIlv0BtlqF8wpgFmKpnI=,tag:ZVQIFfBuCxEAHWRn2AbSew==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:Dvk5nO4=,iv:nglo4/5LuU7FLx9n/607Xx5+2DCjjXWXVInBPs/XPPo=,tag:Rvaa6sIJMKjvkK3G656hog==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:lc345UBXtwzXHCXKki70AavnPQ==,iv:se87VzFod6+0GCGPO1gW0FosdoWRYSImaqBQl41eFo8=,tag:ygHtQzbEnZtWIf5y7qeRtQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1865axnecqy9eccq9fzhpwkz3nkf0sxfeurva6rquyktplhzssv2s32kv5w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRV0V5L3NzTGV3M1R5TC9s
            UDVidXZRVFNXN0RNUEVFdzNneFNSdmg0YUQ4ClBVdXYrRzRBWUN1V2hIZ1A3Q3ZJ
            U3JIbU5qaTh3SlYyT29abGlLSzUyTVkKLS0tIG91b0dtUS82UTRtMUxoWHhkZWVl
            QnQ1T0RCdzdOeWpkMDV3bEtOeWt2Y3cKxXT8fZTAN76T75YVeOVh7EQAGOgDC1Il
            KHyJRZK5TmZ7HLuxv3pFqfC2Fy7NYQCts7BFrTnO4jPFRlO71LVUkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-12T13:26:21Z"
    mac: ENC[AES256_GCM,data:m/k709rrnJz38YTYao18QheAnTQ/6R9aBSCcW8LeKym+3hShNqotCIPuzU+WORnKi29A4kv0h5CKB7ymH4nuxC48rzSal2+D85tQXKb9QBOc7wG7Qzz+vTDw8akB5W8PsnNPvsygN59L7V3rOHTf/j6exzL2sJ01wZVsqsTHhVM=,iv:J/9PhPOPOpOmNm934VaW1sVu+QbG3f9jLhDUUxN7ekY=,tag:wqfl7i6rRRsJZKo5NpEzsQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
