apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
commonLabels:
  app: lidarr
resources:
  - service.yaml
  - deployment.yaml
  - ingress.yaml
  - volume.yaml
  - secret.sops.yaml
  - externalsecret.yaml
