---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: vector-aggregator
spec:
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      vector-aggregator:
        replicas: 3
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: vector-aggregator
        initContainers:
          init-geoip:
            image:
              repository: ghcr.io/maxmind/geoipupdate
              tag: v7.0
              pullPolicy: IfNotPresent
            env:
              - name: GEOIPUPDATE_EDITION_IDS
                value: GeoLite2-Country
              - name: GEOIPUPDATE_FREQUENCY
                value: "0"
              - name: GEOIPUPDATE_VERBOSE
                value: "true"
            envFrom:
              - secretRef:
                  name: vector-maxmind
        containers:
          app:
            image:
              repository: docker.io/timberio/vector
              tag: 0.37.1-alpine@sha256:ced16088cdcfcadd2f471c5760ea3b08bec82b9be00a8b90173b9ade7d001607
            args: ["--config", "/etc/vector/vector.yaml"]
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
    service:
      app:
        controller: vector-aggregator
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "vector.holywoo.cbannister.xyz"
          io.cilium/lb-ipam-ips: "10.45.0.2"
        externalTrafficPolicy: Cluster
        ports:
          http:
            port: 8686
          kubernetes-logs:
            port: 6000
          vyos-syslog:
            port: 6001
          journald-logs:
            port: 6002

    persistence:
      config:
        type: configMap
        name: vector-aggregator-configmap
        globalMounts:
          - path: /etc/vector/vector.yaml
            subPath: vector.yaml
            readOnly: true
      data:
        type: emptyDir
        globalMounts:
          - path: /vector-data-dir
      geoip:
        type: emptyDir
        globalMounts:
          - path: /usr/share/GeoIP
