kind: Secret
apiVersion: v1
metadata:
    name: vector-maxmind
data:
    GEOIPUPDATE_ACCOUNT_ID: ENC[AES256_GCM,data:d8dCfuDfAQA=,iv:nc6VM6zn44t0P7+HiApPFVsVhhY8rGZKL0Gqi2QBA7E=,tag:XzW9JOIFcQ9llw71Ymb+Ew==,type:str]
    GEOIPUPDATE_LICENSE_KEY: ENC[AES256_GCM,data:lb8rClsfhJpQs9c3hO0fk7ndXFbVc71fIxDHETGIApedWhLBIuf9IcEjWqbWYn7bizeINJmfUi8=,iv:nRxEBcx2I1M7/q6utyJYHqAyYQU7Ut0hkslguc1yoPY=,tag:eRU+fPW2NyHL4nounTvHpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1865axnecqy9eccq9fzhpwkz3nkf0sxfeurva6rquyktplhzssv2s32kv5w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRM1djRTl0SVdDbWU0c3Er
            S2VLQWdNRjI5YXZyT0dDS1ZLVWRKdWk5RzJNCmg0TS9zT0k0VVB5VENSTS9Nb0xu
            eGdKMURxdVU4RlJLaFJ1SFVpai8vdHMKLS0tIGVRQUpHVUxCYlBJb2psb3hwVVhy
            cUpVZ2FTT05MTnVEajZsTUpYYVBvT2sK8ffvw4orO90RyCZjzRMzg0zT3VSKA53h
            vnmgwV1aFhOJfBEcKwBmpT25ulUabjH5odQ4AtBwik/cwppvXGtoMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-24T20:19:15Z"
    mac: ENC[AES256_GCM,data:q3oBcjLV/RYGyBK/o7rT/4TpUezW7P9WPAlajppjNrxskhh5lO9JVg7EIGJjD8MeTIZ5lq/Kxqp6Eb3zUNBDHb3fzv8XAVtvWJK2tif7CJTr7ru45uwkKbwJuf9nhKEPtvPBP3lZVcKwm11flVuQkIh1PfwcofUnwPbQNWxDNgk=,iv:1o1WVqv9uu9Y12VnBHaoIYCbFkW7JExIhf0amO6tuPE=,tag:rFwJryrPRFb2XR1x8r2O1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
