apiVersion: v1
kind: Service
metadata:
  name: vector-aggregator
  annotations:
    external-dns.alpha.kubernetes.io/hostname: vector.cbannister.xyz
    io.cilium/lb-ipam-ips: 10.45.0.2
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: vector-aggregator
  ipFamilies:
    - IPv4
  ports:
    - name: http
      nodePort: 32314
      port: 8686
      protocol: TCP
      targetPort: 8686
    - name: journald
      nodePort: 31453
      port: 6002
      protocol: TCP
      targetPort: 6002
    - name: kubernetes
      nodePort: 31155
      port: 6000
      protocol: TCP
      targetPort: 6000
    - name: vyos
      nodePort: 31271
      port: 6001
      protocol: TCP
      targetPort: 6001
