apiVersion: v1
kind: Service
metadata:
  name: sonarr-v4
  annotations:
    external-dns.alpha.kubernetes.io/hostname: sonarr.k8s.holywoo.cbannister.xyz
spec:
  selector:
    app: sonarr
  type: LoadBalancer
  loadBalancerIP: 10.1.12.5
  ipFamilies:
    - IPv4
  ports:
    - name: http
      port: 80
      targetPort: web
      protocol: TCP
