---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - podmonitor.yaml
configMapGenerator:
  - name: dnsdist-config
    files:
      - config/dnsdist.conf.lua
