apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: dnsdist
  namespace: network
  labels:
    app: dnsdist
spec:
  selector:
    matchLabels:
      app: dnsdist
  namespaceSelector:
    matchNames:
      - network
  podMetricsEndpoints:
    - port: metrics
      interval: 15s
      path: /metrics
      scheme: http
