apiVersion: v1
kind: Service
metadata:
  name: dnsdist
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.42.52
  selector:
    app: dnsdist
  ports:
    - port: 53
      targetPort: 5353
      protocol: UDP
      name: dns-udp
