machine:
  kubelet:
    extraArgs:
      image-gc-high-threshold: "55"
      image-gc-low-threshold: "50"
      rotate-server-certificates: "true"
    nodeIP:
      validSubnets:
        - 192.168.42.0/24

  install:
    disk: /dev/sda # The disk used for installations.
    image: ghcr.io/siderolabs/installer:v1.6.4 # Allows for supplying the image used to perform the installation.
    wipe: false # Indicates if the installation disk should be wiped at installation time.

    diskSelector:
      size: "< 1TB"

    extraKernelArgs:
      - mitigations=off

  network:
    interfaces:
      - interface: eno1
        dhcp: true
        vip:
          ip: 192.168.42.254
  features:
    kubePrism:
      enabled: true
      port: 7445

cluster:
  network:
    podSubnets:
      - 10.42.0.0/16
    serviceSubnets:
      - 10.43.0.0/16
    cni:
      name: none
  proxy:
    disabled: true
