version: v1alpha1
debug: false
persist: true
machine:
    type: worker
    token: 66bjaw.0qg9p3q2nrfs2qcr
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQakNCOGFBREFnRUNBaEFFRUJDUUFxVm5VN3U1VXdxNCtIQU1NQVVHQXl0bGNEQVFNUTR3REFZRFZRUUsKRXdWMFlXeHZjekFlRncweU5EQXlNVE14TURFeE1EbGFGdzB6TkRBeU1UQXhNREV4TURsYU1CQXhEakFNQmdOVgpCQW9UQlhSaGJHOXpNQ293QlFZREsyVndBeUVBdlZxV2poM0N3QTE5Q09aVXZ4SzJFeUI5bXdMMzV4WmJ5SmQ5CjY0bUprQjJqWVRCZk1BNEdBMVVkRHdFQi93UUVBd0lDaERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUkKS3dZQkJRVUhBd0l3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVbGZTRit5Y1dHd25vMjU4RQp1V3JUYjdGMXRIVXdCUVlESzJWd0EwRUFTTSt0OVN2OE1vTXpndVNVZ2pwV05pMHlVK282YlNDTXdwcXIzMFEzCkNYcHBtd2JCcTB4bHplbHZxSGhwckVJWE1aSFlTYXViR2N0N2VsbTM3MlZ6Q0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: ""
    certSANs:
        - 127.0.0.1
        - 192.168.42.254
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.29.1
        extraArgs:
            image-gc-high-threshold: "55"
            image-gc-low-threshold: "50"
            rotate-server-certificates: "true"
        defaultRuntimeSeccompProfileEnabled: true
        nodeIP:
            validSubnets:
                - 192.168.42.0/24
        disableManifestsDirectory: true
    network:
        interfaces:
            - interface: enp3s0
              dhcp: true
            - interface: enp114s0
              dhcp: true
            - interface: enp115s0
              dhcp: true
    install:
        disk: /dev/sda
        diskSelector:
            type: ssd
        extraKernelArgs:
            - mitigations=off
        image: ghcr.io/siderolabs/installer:v1.6.4
        wipe: false
    features:
        rbac: true
        stableHostname: true
        apidCheckExtKeyUsage: true
        diskQuotaSupport: true
        kubePrism:
            enabled: true
            port: 7445
cluster:
    id: HPMjWn4s5A97dD1sCeVcVthOCTkPpvg95kx4aqnuGgM=
    secret: SlO9RVR8TEhJP+fqNWyEubEs4AEC6hIR17rnuLzXxRo=
    controlPlane:
        endpoint: https://192.168.42.254:6443
    network:
        cni:
            name: none
        dnsDomain: cluster.local
        podSubnets:
            - 10.42.0.0/16
        serviceSubnets:
            - 10.43.0.0/16
    token: 2lp7e9.b8p2urqguevoh7wb
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpakNDQVRDZ0F3SUJBZ0lSQUp2ZEFldDlETmN4QTNFWnAwakR0amN3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOREF5TVRNeE1ERXhNRGxhRncwek5EQXlNVEF4TURFeApNRGxhTUJVeEV6QVJCZ05WQkFvVENtdDFZbVZ5Ym1WMFpYTXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CCkJ3TkNBQVR4akdRcUNxbSs3RS81QTFMVTZmd0s1T1NjWHl5RUhOZENwY0VRaFMvN1Q2dkp6NzBGUHlFQ0FDbkwKNHVBV3VkWTdiTVk3bW80RjB1MkU3TUhWa2o3K28yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXdIUVlEVlIwbApCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPCkJCWUVGQUIzUGFCcloybTVaRHBObFBuNGJld0tyMlBmTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFDQy8wb1YKYVh0SDZnLzRMREJ5N2RiNUJzTlo2Yk9HdUUvdGtkdHo2VlZuMFFJZ0dvTVpaNU96eHdSbjRvcS9ueTl1Y3hzMQpBclRzb1FRUkowVzI3VFplQ1RVPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: ""
    proxy:
        disabled: true
    discovery:
        enabled: true
        registries:
            kubernetes:
                disabled: true
            service: {}
