apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
spec:
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      hostname: lidarr
      volumes:
        - name: tmp
          emptyDir: {}
        - name: config
          persistentVolumeClaim:
            claimName: lidarr-config
        - name: lidarr-music-bighorse
          persistentVolumeClaim:
            claimName: lidarr-music-bighorse
        - name: horsepc-sabnzbd-complete
          persistentVolumeClaim:
            claimName: horsepc-sabnzbd-complete
      containers:
        - name: lidarr
          image: ghcr.io/onedr0p/lidarr-develop:rolling@sha256:58ccc58f345c48645b81327989cb0b6b498e2894f59c6cec3be25707c8aa022d
          imagePullPolicy: "IfNotPresent"
          env:
            - name: DOTNET_EnableDiagnostics
              value: "0"
            - name: DOTNET_gcServer
              value: "1"
          securityContext:
            runAsUser: 568
            runAsGroup: 586
            runAsNonRoot: true
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: 1000m
              memory: 1Gi
            limits:
              memory: 4Gi
              cpu: 5000m
          ports:
            - containerPort: 8686
              name: web
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: config
              mountPath: /config
              readOnly: false
            - name: lidarr-music-bighorse
              mountPath: /data/media/music
            - name: horsepc-sabnzbd-complete
              mountPath: /data/usenet/complete/lidarr
              subPath: lidarr
          startupProbe:
            httpGet:
              path: /ping
              port: web
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ping
              port: web
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
