apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
commonLabels:
  app: lidarr
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: lidarr-config
    files:
      - config.xml=files/config.xml
