apiVersion: v1
kind: PersistentVolume
metadata:
  name: lidarr-music-horsepc
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb-horsepc
  capacity:
    storage: 100Gi
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1001
    - gid=1001
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino # required to prevent data corruption
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    # volumeHandle format: {smb-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: horsepc#lidarr#music
    volumeAttributes:
      source: //horsepc/music
      subDir: lidarr
    nodeStageSecretRef:
      name: smb-horsepc
      namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-music-horsepc
spec:
  volumeMode: Filesystem
  volumeName: lidarr-music-horsepc
  storageClassName: smb-horsepc
  resources:
    requests:
      storage: 100Gi
  accessModes:
    - ReadWriteOnce
