apiVersion: v1
kind: PersistentVolume
metadata:
  name: lidarr-music-bighorse
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb-bighorse
  capacity:
    storage: 1000Gi
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=568
    - gid=568
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino # required to prevent data corruption
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    # volumeHandle format: {smb-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: bighorse#lidarr
    volumeAttributes:
      source: //truenas/lidarr
    nodeStageSecretRef:
      name: smb-bighorse
      namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-music-bighorse
spec:
  volumeMode: Filesystem
  volumeName: lidarr-music-bighorse
  storageClassName: smb-bighorse
  resources:
    requests:
      storage: 1000Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-media-covers
spec:
  resources:
    requests:
      storage: 10Gi
  storageClassName: smb-horsepc
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-config
spec:
  storageClassName: bighorse-nfs
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
