apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
spec:
  selector:
    matchLabels:
      app: pihole
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pihole
    spec:
      volumes:
        - name: config
          configMap:
            name: pihole-config
        - name: etc-pihole
          persistentVolumeClaim:
            claimName: pihole-config
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: pihole
      containers:
        - name: pihole
          image: ghcr.io/pi-hole/pihole:latest@sha256:8077053835c2d2449041adad0c272d6e5fea3df91c5dfc3dae2bd950999c3118
          imagePullPolicy: "IfNotPresent"
          # securityContext:
          # readOnlyRootFilesystem: true
          resources:
            requests:
              memory: "200Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /etc/pihole
              name: etc-pihole
            - mountPath: /etc/pihole/adlists.list
              name: config
              subPath: adlist.txt
            - mountPath: /etc/pihole/blacklist.txt
              name: config
              subPath: blocklist.txt
            - mountPath: /etc/pihole/whitelist.txt
              name: config
              subPath: allowlist.txt
            - mountPath: /etc/dnsmasq.d/99-domains.conf
              name: config
              subPath: domains.conf
          env:
            - name: WEB_PORT
              value: "80"
            - name: VIRTUAL_HOST
              value: pihole
            - name: WEBPASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: pihole-password
            - name: PIHOLE_DNS_
              value: 10.0.0.1;10.0.0.1
          ports:
            - containerPort: 80
              name: web
            - containerPort: 53
              protocol: UDP
            - containerPort: 53
              protocol: TCP
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /admin/index.php
              port: web
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
