apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
commonLabels:
  app: pihole
resources:
  - statefulset.yaml
  - service.yaml
  - ingress.yaml
configMapGenerator:
  - name: pihole-config
    files:
      - adlist.txt=config/adlist.txt
      - whitelist.txt=config/allowlist.txt
      - blacklist.txt=config/blocklist.txt
      - domains.conf=config/domains.conf
secretGenerator:
  - name: pihole-password
    options:
      disableNameSuffixHash: true
    files:
      - password=config/password.sops.txt
