apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: &name pihole
spec:
  selector:
    matchLabels:
      app: *name
  serviceName: pihole
  replicas: 2
  template:
    metadata:
      labels:
        app: *name
    spec:
      volumes:
        - name: config
          configMap:
            name: pihole-config
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: *name
      containers:
        - name: pihole
          image: ghcr.io/pi-hole/pihole:2024.02.0
          imagePullPolicy: "IfNotPresent"
          # securityContext:
          # readOnlyRootFilesystem: true
          resources:
            requests:
              memory: &ram "1Gi"
              cpu: "500m"
            limits:
              memory: *ram
          volumeMounts:
            - mountPath: /etc/pihole
              name: pihole-config
            - mountPath: /etc/pihole/adlists.list
              name: config
              subPath: adlist.txt
            - mountPath: /etc/pihole/blacklist.txt
              name: config
              subPath: blocklist.txt
            - mountPath: /etc/pihole/whitelist.txt
              name: config
              subPath: allowlist.txt
            - mountPath: /etc/dnsmasq.d/99-domains.conf
              name: config
              subPath: domains.conf
          env:
            - name: WEB_PORT
              value: "80"
            - name: VIRTUAL_HOST
              value: pihole
            - name: WEBPASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: pihole-password
            - name: PIHOLE_DNS_
              value: 192.168.42.1;10.0.0.1
          ports:
            - containerPort: 80
              name: web
            - containerPort: 53
              protocol: UDP
            - containerPort: 53
              protocol: TCP
          startupProbe:
            failureThreshold: 10
            httpGet:
              path: /admin/index.php
              port: web
              scheme: HTTP
            periodSeconds: 5
            timeoutSeconds: 5
          livenessProbe: &probe
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 6
            exec:
              command:
                - nslookup
                - google.com.
                - 127.0.0.1
          readinessProbe:
            <<: *probe
            failureThreshold: 3
            successThreshold: 3
  volumeClaimTemplates:
    - metadata:
        name: pihole-config
      spec:
        storageClassName: ceph-block
        resources:
          requests:
            storage: 1Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
