apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  labels:
    app: qbittorrent
spec:
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      hostname: qbittorrent
      volumes:
        - name: arr-media
          persistentVolumeClaim:
            claimName: bighorse-arr-media
        - name: config
          persistentVolumeClaim:
            claimName: qbittorrent-config
        - name: scripts
          configMap:
            name: qbittorrent-scripts
            defaultMode: 0775
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [10000]
        seccompProfile: { type: RuntimeDefault } 
      containers:
        - name: qbittorent
          image: ghcr.io/onedr0p/qbittorrent:5.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Europe/London
            - name: QBITTORRENT__PORT
              value: "80"
            - name: QBITTORRENT__BT_PORT
              value: "50413"
            - name: QBT_Preferences__WebUI__AlternativeUIEnabled
              value: "false"
            - name: QBT_Preferences__WebUI__AuthSubnetWhitelistEnabled
              value: "true"
            - name: QBT_Preferences__WebUI__AuthSubnetWhitelist
              value: |-
                10.42.0.0/16, 10.45.0.0/24
            - name: QBT_Preferences__WebUI__LocalHostAuth
              value: "false"
            - name: QBT_BitTorrent__Session__DefaultSavePath
              value: /data/torrents/complete
            - name: QBT_BitTorrent__Session__TempPath
              value: /data/torrents/incomplete
          envFrom:
            - secretRef:
                name: qbittorrent-secret
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: { drop: ["ALL"] }
          ports:
            - containerPort: 80
              name: web
            - containerPort: 50413
              name: bt
          resources:
            requests:
              cpu: 100m
            limits:
              memory: 16Gi
          volumeMounts:
            - name: config
              mountPath: /config
            - name: arr-media
              mountPath: /data/torrents
              subPath: torrents
            - name: scripts
              mountPath: /scripts
              readOnly: true
