---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml
configMapGenerator:
  - name: qbittorrent-loki-rules
    files:
      - qbittorrent.yaml=./resources/lokirule.yaml
    options:
      labels:
        loki_rule: "true"

