---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name smartctl
spec:
  staticConfigs:
    - targets:
      - pve.cbannister.casa:9633
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
