apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
  labels:
    app: prowlarr
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  labels:
    app: prowlarr
spec:
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      volumes:
        - name: prowlar-config
          persistentVolumeClaim:
            claimName: prowlarr-config
        - name: prowlar-backups
          emptyDir: {}
      containers:
        - name: prowlarr
          image: ghcr.io/onedr0p/prowlarr-develop:1.3.1.2796
          imagePullPolicy: "IfNotPresent"
          env:
            - name: COMPlus_EnableDiagnostics
              value: "0"
          securityContext:
            runAsUser: 568
            runAsNonRoot: true
            readOnlyRootFilesystem: true
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 9696
              name: web
          volumeMounts:
            - name: prowlar-config
              mountPath: /config
            - name: prowlar-backups
              mountPath: /tmp/prowlarr_backup
          # livenessProbe:
          #   httpGet:
          #     path: /api/v1/health
          #     port: web
          #   initialDelaySeconds: 10
          #   periodSeconds: 20
