apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - files:
      - Indexers/definitions/v8/abnzb.yml
      - Indexers/definitions/v8/althub.yml
      - Indexers/definitions/v8/animetosho-usenet.yml
      - Indexers/definitions/v8/dognzb.yml
      - Indexers/definitions/v8/drunkenslug.yml
      - Indexers/definitions/v8/miatrix.yml
      - Indexers/definitions/v8/newz-complex.yml
      - Indexers/definitions/v8/newz69.yml
      - Indexers/definitions/v8/ninjacentral.yml
      - Indexers/definitions/v8/nzb.su.yml
      - Indexers/definitions/v8/nzbcat.yml
      - Indexers/definitions/v8/nzbfinder.yml
      - Indexers/definitions/v8/nzbgeek.yml
      - Indexers/definitions/v8/nzbndx.yml
      - Indexers/definitions/v8/nzbnoob.yml
      - Indexers/definitions/v8/nzbplanet.yml
      - Indexers/definitions/v8/nzbstars.yml
      - Indexers/definitions/v8/simplynzbs.yml
      - Indexers/definitions/v8/spotnzb.yml
      - Indexers/definitions/v8/tabularasa.yml
    name: v8-defs
