apiVersion: v1
kind: Service
metadata:
  labels:
    app: prowlarr
  name: prowlarr-v4
spec:
  selector:
    app: prowlarr
  type: LoadBalancer
  loadBalancerIP: 10.1.12.2
  ipFamilies:
    - IPv4
  ports:
    - name: http
      port: 80
      targetPort: 9696
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prowlarr
  name: prowlarr-v6
spec:
  selector:
    app: prowlarr
  type: LoadBalancer
  ipFamilies:
    - IPv6
  ipFamilyPolicy: SingleStack
  loadBalancerIP: fdff:cafe::3
  ports:
    - name: http
      port: 80
      targetPort: 9696
      protocol: TCP
