apiVersion: v1
kind: Service
metadata:
  labels:
    app: prowlarr
  name: prowlarr
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.1.12.2
spec:
  selector:
    app: prowlarr
  type: LoadBalancer
  ipFamilies:
    - IPv4
    - IPv6
  ports:
    - name: http
      port: 80
      targetPort: 9696
      protocol: TCP
