apiVersion: v1
kind: Service
metadata:
  labels:
    app: prowlarr
  name: prowlarr
spec:
  selector:
    app: prowlarr
  type: LoadBalancer
  loadBalancerIP: 10.1.12.2
  ports:
    - name: http
      port: 80
      targetPort: 9696
      protocol: TCP
