---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  drain:
    desc: Drain a node
    summary: |
      Args:
        node: Node to drain (required)
    cmd: kubectl drain {{.node}} --ignore-daemonsets --delete-local-data --force
    requires:
      vars: ["node"]

  delete-failed-pods:
    desc: Deletes pods with a fucked status
    cmds:
      - for: ["Evicted", "Failed", "Succeeded"]
        cmd: kubectl delete pods --field-selector status.phase={{.ITEM}} -A --ignore-not-found=true
