apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
spec:
  storageClassName: bighorse-nfs
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
