apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
commonLabels:
  app: sonarr
resources:
  - deployment.yaml
  - service.yaml
  - volumes.yaml
secretGenerator:
  - name: sonarr-env-config
    envs:
      - ./config/postgres.env
