# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - deployment.yaml
  - service.yaml
  - volumes.yaml
configMapGenerator:
  - name: sonarr-env-config
    envs:
      - ./config/postgres.env
  - name: sonarr-scripts
    files:
      - refresh-tba.sh=scripts/refresh-tba.sh
