apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
spec:
  interval: 5m
  targetNamespace: kube-system
  releaseName: cilium
  chart:
    spec:
      chart: cilium
      version: 1.14.2
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: cilium-values
