apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cilium
spec:
  interval: 5m
  url: https://helm.cilium.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
spec:
  interval: 5m
  targetNamespace: kube-system
  releaseName: cilium
  chart:
    spec:
      chart: cilium
      version: v1.14.1
      sourceRef:
        kind: HelmRepository
        name: cilium
      interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: cilium-values
