apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cilium
spec:
  interval: 30m
  targetNamespace: kube-system
  releaseName: cilium
  chart:
    spec:
      chart: cilium
      version: 1.15.0-pre.3
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: cilium-values
