apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
commonLabels:
  app: cilium
resources:
  - bgp.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: cilium-values
    files:
      - values.yaml=./values.yaml
configurations:
  - kustomizeconfig.yaml
