cluster:
  name: default
hubble:
  relay:
    enabled: true
  ui:
    enabled: false
ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDRList: 10.42.0.0/16
k8sServiceHost: 10.0.4.147
k8sServicePort: 6443
kubeProxyReplacement: strict
operator:
  replicas: 1
serviceAccounts:
  cilium:
    name: cilium
  operator:
    name: cilium-operator
tunnel: vxlan
devices: ens+
l2announcements:
  enabled: true
k8sClientRateLimit:
  qps: 30
  burst: 50
