apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex
  annotations:
    external-dns.alpha.kubernetes.io/target: external.cbannister.xyz
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Real-IP $remote_addr;
spec:
  ingressClassName: external
  rules:
    - host: &host plex.cbannister.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plex
                port:
                  number: 80
  tls:
    - hosts:
        - *host
