apiVersion: v1
kind: Service
metadata:
  name: plex
  annotations:
    io.cilium/lb-ipam-ips: 192.168.42.210
spec:
  selector:
    app: plex
  type: LoadBalancer
  ipFamilies:
    - IPv4
  ports:
    - name: web
      port: 80
      targetPort: 32400
      protocol: TCP
    - name: plex
      port: 32400
      targetPort: 32400
      protocol: TCP
