apiVersion: v1
kind: Service
metadata:
  name: plex
spec:
  selector:
    app: plex
  type: ClusterIP
  ipFamilies:
    - IPv4
  ports:
    - name: plex
      port: 32400
      targetPort: web
      protocol: TCP
