apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plex
spec:
  serviceName: plex
  replicas: 1
  selector:
    matchLabels:
      app: plex
  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: ceph-block
        volumeMode: Filesystem
  template:
    metadata:
      labels:
        app: plex
    spec:
      runtimeClassName: nvidia
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
      nodeSelector:
        nas: local
      volumes:
        - name: transcode
          emptyDir: {}
        - name: arr-media
          persistentVolumeClaim:
            claimName: bighorse-arr-media
            readOnly: true
      containers:
        - name: plex
          image: ghcr.io/onedr0p/plex:1.40.0.7998-c29d4c0c8
          env:
            - name: TZ
              value: Europe/London
            - name: PLEX_ADVERTISE_URL
              value: https://plex.cbannister.xyz:443,http://192.168.42.210:32400
            - name: PLEX_NO_AUTH_NETWORKS
              value: 192.168.1.0/24
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "all"
          resources:
            requests:
              cpu: 1000m
              memory: 4096Mi
              nvidia.com/gpu: 1
            limits:
              memory: 4096Mi
              nvidia.com/gpu: 1
          ports:
            - containerPort: 32400
              name: plex
          volumeMounts:
            - name: transcode
              mountPath: /transcode
            - name: config
              mountPath: /config
            - name: arr-media
              mountPath: /data
