apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plex
spec:
  serviceName: plex
  replicas: 1
  selector:
    matchLabels:
      app: plex
  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 100Gi
        storageClassName: ceph-filesystem
        volumeMode: Filesystem
  template:
    metadata:
      labels:
        app: plex
    spec:
      runtimeClassName: nvidia
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
      nodeSelector:
        nas: local
      volumes:
        - name: transcode
          emptyDir: {}
        - name: arr-media
          persistentVolumeClaim:
            claimName: bighorse-arr-media
            readOnly: true
      containers:
        - name: plex
          image: ghcr.io/onedr0p/plex:1.40.5.8921-836b34c27@sha256:154636521a4ea14b3b0720443e7714f53318aeacb569fc00f4221969e2978b7b
          env:
            - name: TZ
              value: Europe/London
            - name: PLEX_ADVERTISE_URL
              value: https://plex.cbannister.xyz:443,http://10.45.0.20:32400
            - name: PLEX_NO_AUTH_NETWORKS
              value: 10.0.0.0/8
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "all"
          resources:
            requests:
              cpu: 1000m
              memory: 4096Mi
              nvidia.com/gpu: 1
            limits:
              memory: 4096Mi
              nvidia.com/gpu: 1
          ports:
            - containerPort: 32400
              name: plex
          volumeMounts:
            - name: transcode
              mountPath: /transcode
            - name: config
              mountPath: /config
            - name: arr-media
              mountPath: /data
          livenessProbe: &livenessProbe
            httpGet:
              path: /identity
              port: plex
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readinessProbe: *livenessProbe
          startupProbe: *livenessProbe
