---
nameReference:
  - kind: ConfigMap
    version: v1
    fieldSpecs:
      - path: spec/values/persistence/config/name
        kind: HelmRelease
  - kind: Sercret
    version: v1
    fieldSpecs:
      - path: spec/values/persistence/creds/name
        kind: HelmRelease
