apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ns.yaml
  - ./prometheus
  - ./unpoller
  - ./grafana
  - ./kube-state-metrics
  - ./node-exporter
