apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
spec:
  interval: 5m
  targetNamespace: nvidia-device-plugin
  releaseName: nvidia-device-plugin
  chart:
    spec:
      chart: nvidia-device-plugin
      version: 0.14.2
      sourceRef:
        kind: HelmRepository
        name: nvdp
        namespace: flux-system
      interval: 30m
  values:
    config:
      name: nvidia-device-plugin-config
    gfd:
      enabled: true
