apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nvdp
spec:
  interval: 5m
  url: https://nvidia.github.io/k8s-device-plugin
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
spec:
  interval: 5m
  targetNamespace: nvidia-device-plugin
  releaseName: nvidia-device-plugin
  chart:
    spec:
      chart: nvidia-device-plugin
      version: 0.14.1
      sourceRef:
        kind: HelmRepository
        name: nvdp
      interval: 30m
  values:
    config.name: nvidia-device-plugin-config
