# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname nvidia-device-plugin 
  namespace: flux-system
spec:
  targetNamespace: nvidia-device-plugin
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  path: ./k8s/apps/nvidia-device-plugin/nvidia-device-plugin/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 10m
  retryInterval: 1m
  timeout: 5m
