apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-subnet-router
spec:
  selector:
    matchLabels:
      app: tailscale-subnet-router
  template:
    metadata:
      labels:
        app: tailscale-subnet-router
    spec:
      hostname: tailscale-subnet-router-a
      serviceAccountName: tailscale-subnet-router
      containers:
        - name: tailscale-subnet-router
          image: ghcr.io/tailscale/tailscale:v1.58.2
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "1Gi"
          env:
            - name: TS_KUBE_SECRET
              value: tailscale-state
            - name: TS_USERSPACE
              value: "true"
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-auth
                  key: authkey
            - name: TS_ROUTES
              value: 192.168.1.0/24,10.0.0.0/21,192.168.42.0/24
            - name: TS_EXTRA_ARGS
              value: "--advertise-exit-node"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            privileged: false
