apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
resources:
  - ./deployment.yaml
  - ./rbac.yaml
secretGenerator:
  - name: tailscale-auth
    files:
      - authkey=config/authkey.sops.txt
