---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - statefulset.yaml
  - service.yaml
  - ingress.yaml
configMapGenerator:
  - name: tautulli-scripts
    files:
      - scripts/select_tmdb_poster.py
labels:
  - pairs:
      app.kubernetes.io/name: tautulli
    includeSelectors: true
    includeTemplates: true
