---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sabnzbd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sabnzbd-secret
    template:
      engineVersion: v2
      data:
        CROSS_SEED_API_KEY: "{{ .CROSS_SEED_API_KEY }}"
        CROSS_SEED_HOST: "cross-seed.default.svc.cluster.local"
        CROSS_SEED_PORT: "80"
        CROSS_SEED_SLEEP_INTERVAL: "0"
  dataFrom:
    - extract:
        key: cross-seed
