apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
commonLabels:
  app: sabnzbd
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - volume.yaml
configMapGenerator:
  - name: sabnzbd-scripts
    files:
      - clean.py=config/clean.py
      - replace_for.py=config/replace_for.py
