apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-filesystem
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
