name: "Meta Sync labels"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - .github/labels.yaml
      - .github/workflows/meta-sync-labels.yaml

jobs:
  labels:
    name: Sync Labels
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: Sync Labels
        uses: EndBug/label-sync@da00f2c11fdb78e4fae44adac2fdd713778ea3e8 # renovate: tag=v2.3.2
        with:
          config-file: .github/labels.yaml
          delete-other-labels: true
          request-token: "{{ github.token }}"
          token: "{{ github.token }}"
