---
- name: Cluster kube-vip
  hosts: control_plane
  serial: 1
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 2 seconds...
      ansible.builtin.pause:
        seconds: 2
  tasks:
    - name: Ensure Kubernetes is running
      ansible.builtin.include_role:
        name: xanmanning.k3s
        public: true
      vars:
        k3s_state: started

    - name: Upgrade kube-vip
      ansible.builtin.template:
        src: templates/kube-vip-ds.yaml.j2
        dest: "{{ k3s_server_manifests_dir }}/kube-vip-ds.yaml"
        mode: preserve

    - name: Remove kube-vip static pod
      notify: Restart k3s
      ansible.builtin.file:
        path: "/var/lib/rancher/k3s/agent/pod-manifests//kube-vip-static-pod.yaml"
        state: absent
  handlers:
    - name: Restart k3s
      ansible.builtin.service:
        name: k3s
        state: restarted
