- name: Matchbox Setup
  become: true
  gather_facts: true
  hosts: vyos
  vars:
    talos_version: v1.8.1
  tasks:
    - name: Matchbox
      block:
        - name: Machbox | Configure Directory
          loop:
            - /config/containers/matchbox/assets
            - /config/containers/matchbox/profiles
            - /config/containers/matchbox/groups
          ansible.builtin.file:
            dest: "{{ item }}"
            state: directory
            mode: "0777"
            owner: vyos
            group: vyattacfg

        - name: Matchbox | Talos
          loop: "{{ groups['k8s'] | flatten(levels=1) }}"
          loop_control:
            loop_var: name
          vars:
            node: "{{ hostvars[name] }}"
          include_tasks: "matchbox-talos.yaml"

    - name: TFTP Setup
      block:
        - name: Configure bootdir
          ansible.builtin.file:
            dest: /config/tftpboot
            state: directory
            mode: "0777"
            owner: tftp
            group: tftp
        - name: Fetch pxe boot loaders
          loop:
            - undionly.kpxe
            - ipxe.efi
          ansible.builtin.get_url:
            url: https://boot.ipxe.org/{{ item }}
            dest: /config/tftpboot/{{ item }}
            mode: "0755"
            owner: tftp
            group: tftp
        - name: Setup undionly.kpxe0
          ansible.builtin.command:
            cmd: cp /config/tftpboot/undionly.kpxe /config/tftpboot/undionly.kpxe0
            creates: /config/tftpboot/undionly.kpxe0
