- name: Create Asset Directory
  ansible.builtin.file:
    dest: "/config/containers/matchbox/assets/{{ node.talos.schematic_id}}"
    state: directory
    mode: "0777"
    owner: vyos
    group: vyattacfg


- name: Fetch Talos
  loop:
    - file: initramfs-amd64.xz
      sha: "{{ node.talos.initramfs_sha }}"
    - file: kernel-amd64
      sha: "{{ node.talos.kernel_sha }}"
  ansible.builtin.get_url:
    url: https://factory.talos.dev/image/{{ node.talos.schematic_id  }}/{{ talos_version }}/{{ item.file }}
    dest: /config/containers/matchbox/assets/{{ node.talos.schematic_id }}/{{ item.file }}
    checksum: sha256:{{ item.sha }}
    decompress: no
    owner: vyos
    group: vyattacfg
    mode: "0644"
    timeout: 60

- name: Setup Profile
  ansible.builtin.template:
    dest: /config/containers/matchbox/profiles/{{ name }}.json
    src: templates/matchbox/profile.json.j2
    owner: vyos
    group: vyattacfg
    mode: "0644"

- name: Setup Group
  ansible.builtin.template:
    dest: /config/containers/matchbox/groups/{{ name }}.json
    src: templates/matchbox/group.json.j2
    owner: vyos
    group: vyattacfg
    mode: "0644"

- name: Talos Config
  ansible.builtin.template:
    dest: /config/containers/matchbox/assets/{{ name }}.yaml
    src: files/talos/holywoo-{{ name }}.yaml
    owner: vyos
    group: vyattacfg
    mode: "0644"

