apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - pvc.yaml
  - service.yaml
  - ingress.yaml
  - rbac.yaml
  - externalsecret.yaml
configMapGenerator:
  - name: postgres-jdbc
    files:
      - postgres.jar=https://jdbc.postgresql.org/download/postgresql-42.7.3.jar
